spring.application.name=mundoanimal
spring.datasource.url=jdbc:postgresql://dpg-d8fc1tt53gjs739vticg-a.oregon-postgres.render.com/mundo_animal_vbt8
spring.datasource.username=mundo_animal_vbt8_user
spring.datasource.password=mWgUSdWK9eGwNLnT5rgWVczcI1Vnwjmn

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.swagger-ui.path=/aula/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# cloudinary.cloud-name=decaqkuve
# cloudinary.api-key=817985234265266
# cloudinary.api-secret=3rogajIherlIitqzmhhPWXLdYFc
# springdoc.swagger-ui.url=/v3/api-docs
# server.forward-headers-strategy=framework